workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      flutter: stable
      groups:
        - appetize_credentials
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter build ipa
        script: |
          flutter build ios
          xcodebuild -workspace "ios/Runner.xcworkspace" \
            -scheme "Runner" \
            -configuration "Debug" \
            -sdk iphonesimulator \
            -derivedDataPath ios/output
          cd ios/output/Build/Products/Debug-iphonesimulator
          zip -r ios_app.zip Runner.app
    artifacts:
      - ios/output/Build/Products/Debug-iphonesimulator/*.zip
    publishing:
      scripts:
        - name: Publish App to Appetize
          script: |
            zipPath="ios/output/Build/Products/Debug-iphonesimulator/ios_app.zip"
            echo $(curl --location --request POST "https://$APPETIZE_API_TOKEN@api.appetize.io/v1/apps/$APPETIZE_APP_PUBLIC_KEY" --form "file=@$zipPath")