workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      flutter: stable
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter build ipa
        script: |
          flutter build ios --release --no-codesign
          cd build/ios/iphoneos/
          mkdir Payload
          mv Runner.app Payload
          zip -r Payload.zip Payload
          mv Payload.zip Runner.ipa
    artifacts:
      - build/ios/iphoneos/*.ipa